//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImgUrl { get; set; }
        public string HtmlContent { get; set; }
        public string Time { get; set; }
        public Nullable<int> BlogTypeId { get; set; }
        public Nullable<int> UserInfoId { get; set; }
    
        public virtual BlogType BlogType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
